task:
  env:
    CFLAGS: -I/usr/local/include
    LDFLAGS: -L/usr/local/lib
    LD_LIBRARY_PATH: /usr/local/lib
    PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/local/libdata/pkgconfig"
    PATH: "${PATH}:/usr/local/sbin:/usr/sbin"
    ibmtpm_name: ibmtpm1628
  freebsd_instance:
    matrix:
      image_family: freebsd-12-1-snap
  install_script:
    - pkg update -f
    - pkg upgrade -y
    - pkg install -y bash gmake coreutils libtool pkgconf autoconf autoconf-archive e2fsprogs-libuuid py37-yaml expect
    - pkg install -y automake glib dbus dbus-glib cmocka wget git openssl json-c vim
    - wget --quiet --show-progress --progress=dot:giga "https://downloads.sourceforge.net/project/ibmswtpm2/$ibmtpm_name.tar.gz"
    - shasum -a256 $ibmtpm_name.tar.gz | grep ^a8e874e7a1ae13a1290d7679d846281f72d0eb6a5e4cfbafca5297dbf4e29ea3
    - mkdir -p $ibmtpm_name
    - tar xvf $ibmtpm_name.tar.gz -C $ibmtpm_name && cd $ibmtpm_name/src
    - sed -i '' -e 's/gcc/clang/g' makefile
    - sed -i '' -e 's/-Wall //g' makefile
    - sed -i '' -e 's/-Werror //g' makefile
    - gmake -j && cp tpm_server /usr/bin/
    - cd -
    - rm -rf $ibmtpm_name $ibmtpm_name.tar.gz
    - mkdir tss
    - cd tss && git clone https://github.com/tpm2-software/tpm2-tss.git
    - cd tpm2-tss && ./bootstrap && ./configure --disable-doxygen-doc --disable-dependency-tracking --disable-tcti-swtpm && gmake install
    - cd ../../ && rm -rf tss
    - mkdir rm
    - cd rm && git clone https://github.com/tpm2-software/tpm2-abrmd.git && cd tpm2-abrmd
    - ./bootstrap && ./configure --disable-dependency-tracking && gmake install
    - cd ../../ && rm -rf rm
  script:
    - ./bootstrap
    - ./configure --enable-unit=yes --enable-debug=yes --disable-dependency-tracking
    - gmake -j check || { cat test-suite.log; exit 1; }
