task:
  env:
    CFLAGS: -I/usr/local/include
    LDFLAGS: -L/usr/local/lib
    LD_LIBRARY_PATH: /usr/local/lib
    PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/local/libdata/pkgconfig"
    PATH: "${PATH}:/usr/local/sbin:/usr/sbin"
    ibmtpm_name: ibmtpm1637
    TSS2_LOG: "all+ERROR;tcti+TRACE"
  freebsd_instance:
    image_family: freebsd-13-2
  install_script:
    - pkg update -f
    - pkg upgrade -y
    - pkg install -y bash gmake coreutils libtool pkgconf autoconf autoconf-archive e2fsprogs-libuuid py39-yaml expect
    - pkg install -y automake glib dbus dbus-glib cmocka wget git openssl json-c vim hs-pandoc
    - wget --quiet --show-progress --progress=dot:giga "https://downloads.sourceforge.net/project/ibmswtpm2/$ibmtpm_name.tar.gz"
    - shasum -a256 $ibmtpm_name.tar.gz | grep ^dd3a4c3f7724243bc9ebcd5c39bbf87b82c696d1c1241cb8e5883534f6e2e327
    - mkdir -p $ibmtpm_name
    - tar xvf $ibmtpm_name.tar.gz -C $ibmtpm_name && cd $ibmtpm_name/src
    - sed -i '' -e 's/gcc/clang/g' makefile
    - sed -i '' -e 's/-Wall //g' makefile
    - sed -i '' -e 's/-Werror //g' makefile
    - gmake && cp tpm_server /usr/bin/
    - cd -
    - rm -rf $ibmtpm_name $ibmtpm_name.tar.gz
    - mkdir tss
    - cd tss && git clone https://github.com/tpm2-software/tpm2-tss.git
    - cd tpm2-tss && ./bootstrap && ./configure --disable-doxygen-doc --disable-tcti-swtpm --disable-tcti-libtpms --disable-dependency-tracking && gmake -j install
    - cd ../../ && rm -rf tss
    - mkdir rm
    - cd rm && git clone https://github.com/tpm2-software/tpm2-abrmd.git && cd tpm2-abrmd
    - ./bootstrap && ./configure --disable-dependency-tracking && gmake -j install
    - cd ../../ && rm -rf rm
  script:
    - ./bootstrap
    - ./configure --enable-unit=yes --disable-dependency-tracking --disable-fapi
    - gmake -j check || { cat test-suite.log; exit 1; }
