extraction:
  cpp:
    prepare:
      packages:
      - autoconf-archive
      - libcurl4-openssl-dev
      - libjson-c-dev
      - libssl-dev
    after_prepare:
    - cd "$LGTM_WORKSPACE"
    - mkdir installdir
    - wget https://github.com/tpm2-software/tpm2-tss/archive/master.tar.gz
    - tar xf master.tar.gz
    - cd tpm2-tss-master
    - ./bootstrap
    - ./configure --prefix="$LGTM_WORKSPACE/installdir/usr" --disable-doxygen-doc
    - make install
    - export PKG_CONFIG_PATH="$LGTM_WORKSPACE/installdir/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
    - export LD_LIBRARY_PATH="$LGTM_WORKSPACE/installdir/usr/lib:$LD_LIBRARY_PATH"
