# Makefile.in generated by automake 1.14.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



#;**********************************************************************;
#
# Copyright (c) 2015, Intel Corporation
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, 
# this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice, 
# this list of conditions and the following disclaimer in the documentation 
# and/or other materials provided with the distribution.
#
# 3. Neither the name of Intel Corporation nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
# THE POSSIBILITY OF SUCH DAMAGE.
#;**********************************************************************;



am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/tpm2-0-tools
pkgincludedir = $(includedir)/tpm2-0-tools
pkglibdir = $(libdir)/tpm2-0-tools
pkglibexecdir = $(libexecdir)/tpm2-0-tools
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
sbin_PROGRAMS = src/tpm2_listpcrs$(EXEEXT) src/tpm2_quote$(EXEEXT) \
	src/tpm2_takeownership$(EXEEXT) src/tpm2_getpubek$(EXEEXT) \
	src/tpm2_getpubak$(EXEEXT) src/tpm2_getmanufec$(EXEEXT) \
	src/tpm2_akparse$(EXEEXT) src/tpm2_makecredential$(EXEEXT) \
	src/tpm2_activatecredential$(EXEEXT) src/tpm2_hash$(EXEEXT) \
	src/tpm2_nvlist$(EXEEXT) src/tpm2_nvread$(EXEEXT) \
        src/tpm2_nvreadlock$(EXEEXT) \
	src/tpm2_nvwrite$(EXEEXT) src/tpm2_nvdefine$(EXEEXT) \
	src/tpm2_nvrelease$(EXEEXT) src/tpm2_createprimary$(EXEEXT) \
	src/tpm2_create$(EXEEXT) src/tpm2_hmac$(EXEEXT) \
	src/tpm2_certify$(EXEEXT) src/tpm2_readpublic$(EXEEXT) \
	src/tpm2_getrandom$(EXEEXT) src/tpm2_encryptdecrypt$(EXEEXT) \
	src/tpm2_evictcontrol$(EXEEXT) src/tpm2_load$(EXEEXT) \
	src/tpm2_loadexternal$(EXEEXT) src/tpm2_rsadecrypt$(EXEEXT) \
	src/tpm2_rsaencrypt$(EXEEXT) src/tpm2_sign$(EXEEXT) \
	src/tpm2_unseal$(EXEEXT) src/tpm2_verifysignature$(EXEEXT)
subdir = .
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) depcomp \
	ChangeLog INSTALL compile config.guess config.sub install-sh \
	missing ltmain.sh
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
LIBRARIES = $(noinst_LIBRARIES)
ARFLAGS = cru
AM_V_AR = $(am__v_AR_$(V))
am__v_AR_ = $(am__v_AR_$(AM_DEFAULT_VERBOSITY))
am__v_AR_0 = @echo "  AR      " $@;
am__v_AR_1 = 
src_libcommon_a_AR = $(AR) $(ARFLAGS)
src_libcommon_a_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am__objects_1 = src/common.$(OBJEXT) src/debug.$(OBJEXT) \
	src/syscontext.$(OBJEXT) src/CatSizedByteBuffer.$(OBJEXT) \
	src/CopySizedBuffer.$(OBJEXT) src/DecryptEncrypt.$(OBJEXT) \
	src/Entity.$(OBJEXT) src/kdfa.$(OBJEXT) \
	src/LoadExternalHMACKey.$(OBJEXT) src/SessionHmac.$(OBJEXT) \
	src/StartAuthSession.$(OBJEXT) src/TpmCalcPHash.$(OBJEXT) \
	src/TpmHandleToName.$(OBJEXT) src/TpmHash.$(OBJEXT) \
	src/TpmHmac.$(OBJEXT)
am_src_libcommon_a_OBJECTS = $(am__objects_1)
src_libcommon_a_OBJECTS = $(am_src_libcommon_a_OBJECTS)
am__installdirs = "$(DESTDIR)$(sbindir)"
PROGRAMS = $(sbin_PROGRAMS)
am_src_tpm2_activatecredential_OBJECTS =  \
	src/tpm2_activatecredential.$(OBJEXT)
src_tpm2_activatecredential_OBJECTS =  \
	$(am_src_tpm2_activatecredential_OBJECTS)
src_tpm2_activatecredential_LDADD = $(LDADD)
src_tpm2_activatecredential_DEPENDENCIES = src/libcommon.a
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
am_src_tpm2_akparse_OBJECTS = src/tpm2_akparse.$(OBJEXT)
src_tpm2_akparse_OBJECTS = $(am_src_tpm2_akparse_OBJECTS)
src_tpm2_akparse_LDADD = $(LDADD)
src_tpm2_akparse_DEPENDENCIES = src/libcommon.a
am_src_tpm2_certify_OBJECTS = src/tpm2_certify.$(OBJEXT)
src_tpm2_certify_OBJECTS = $(am_src_tpm2_certify_OBJECTS)
src_tpm2_certify_LDADD = $(LDADD)
src_tpm2_certify_DEPENDENCIES = src/libcommon.a
am_src_tpm2_create_OBJECTS = src/tpm2_create.$(OBJEXT)
src_tpm2_create_OBJECTS = $(am_src_tpm2_create_OBJECTS)
src_tpm2_create_LDADD = $(LDADD)
src_tpm2_create_DEPENDENCIES = src/libcommon.a
am_src_tpm2_createprimary_OBJECTS = src/tpm2_createprimary.$(OBJEXT)
src_tpm2_createprimary_OBJECTS = $(am_src_tpm2_createprimary_OBJECTS)
src_tpm2_createprimary_LDADD = $(LDADD)
src_tpm2_createprimary_DEPENDENCIES = src/libcommon.a
am_src_tpm2_encryptdecrypt_OBJECTS =  \
	src/tpm2_encryptdecrypt.$(OBJEXT)
src_tpm2_encryptdecrypt_OBJECTS =  \
	$(am_src_tpm2_encryptdecrypt_OBJECTS)
src_tpm2_encryptdecrypt_LDADD = $(LDADD)
src_tpm2_encryptdecrypt_DEPENDENCIES = src/libcommon.a
am_src_tpm2_evictcontrol_OBJECTS = src/tpm2_evictcontrol.$(OBJEXT)
src_tpm2_evictcontrol_OBJECTS = $(am_src_tpm2_evictcontrol_OBJECTS)
src_tpm2_evictcontrol_LDADD = $(LDADD)
src_tpm2_evictcontrol_DEPENDENCIES = src/libcommon.a
am_src_tpm2_getmanufec_OBJECTS = src/tpm2_getmanufec.$(OBJEXT)
src_tpm2_getmanufec_OBJECTS = $(am_src_tpm2_getmanufec_OBJECTS)
src_tpm2_getmanufec_LDADD = $(LDADD)
src_tpm2_getmanufec_DEPENDENCIES = src/libcommon.a
am_src_tpm2_getpubak_OBJECTS = src/tpm2_getpubak.$(OBJEXT)
src_tpm2_getpubak_OBJECTS = $(am_src_tpm2_getpubak_OBJECTS)
src_tpm2_getpubak_LDADD = $(LDADD)
src_tpm2_getpubak_DEPENDENCIES = src/libcommon.a
am_src_tpm2_getpubek_OBJECTS = src/tpm2_getpubek.$(OBJEXT)
src_tpm2_getpubek_OBJECTS = $(am_src_tpm2_getpubek_OBJECTS)
src_tpm2_getpubek_LDADD = $(LDADD)
src_tpm2_getpubek_DEPENDENCIES = src/libcommon.a
am_src_tpm2_getrandom_OBJECTS = src/tpm2_getrandom.$(OBJEXT)
src_tpm2_getrandom_OBJECTS = $(am_src_tpm2_getrandom_OBJECTS)
src_tpm2_getrandom_LDADD = $(LDADD)
src_tpm2_getrandom_DEPENDENCIES = src/libcommon.a
am_src_tpm2_hash_OBJECTS = src/tpm2_hash.$(OBJEXT)
src_tpm2_hash_OBJECTS = $(am_src_tpm2_hash_OBJECTS)
src_tpm2_hash_LDADD = $(LDADD)
src_tpm2_hash_DEPENDENCIES = src/libcommon.a
am_src_tpm2_hmac_OBJECTS = src/tpm2_hmac.$(OBJEXT)
src_tpm2_hmac_OBJECTS = $(am_src_tpm2_hmac_OBJECTS)
src_tpm2_hmac_LDADD = $(LDADD)
src_tpm2_hmac_DEPENDENCIES = src/libcommon.a
am_src_tpm2_listpcrs_OBJECTS = src/tpm2_listpcrs.$(OBJEXT)
src_tpm2_listpcrs_OBJECTS = $(am_src_tpm2_listpcrs_OBJECTS)
src_tpm2_listpcrs_LDADD = $(LDADD)
src_tpm2_listpcrs_DEPENDENCIES = src/libcommon.a
am_src_tpm2_load_OBJECTS = src/tpm2_load.$(OBJEXT)
src_tpm2_load_OBJECTS = $(am_src_tpm2_load_OBJECTS)
src_tpm2_load_LDADD = $(LDADD)
src_tpm2_load_DEPENDENCIES = src/libcommon.a
am_src_tpm2_loadexternal_OBJECTS = src/tpm2_loadexternal.$(OBJEXT)
src_tpm2_loadexternal_OBJECTS = $(am_src_tpm2_loadexternal_OBJECTS)
src_tpm2_loadexternal_LDADD = $(LDADD)
src_tpm2_loadexternal_DEPENDENCIES = src/libcommon.a
am_src_tpm2_makecredential_OBJECTS =  \
	src/tpm2_makecredential.$(OBJEXT)
src_tpm2_makecredential_OBJECTS =  \
	$(am_src_tpm2_makecredential_OBJECTS)
src_tpm2_makecredential_LDADD = $(LDADD)
src_tpm2_makecredential_DEPENDENCIES = src/libcommon.a
am_src_tpm2_nvdefine_OBJECTS = src/tpm2_nvdefine.$(OBJEXT)
src_tpm2_nvdefine_OBJECTS = $(am_src_tpm2_nvdefine_OBJECTS)
src_tpm2_nvdefine_LDADD = $(LDADD)
src_tpm2_nvdefine_DEPENDENCIES = src/libcommon.a
am_src_tpm2_nvlist_OBJECTS = src/tpm2_nvlist.$(OBJEXT)
src_tpm2_nvlist_OBJECTS = $(am_src_tpm2_nvlist_OBJECTS)
src_tpm2_nvlist_LDADD = $(LDADD)
src_tpm2_nvlist_DEPENDENCIES = src/libcommon.a
am_src_tpm2_nvread_OBJECTS = src/tpm2_nvread.$(OBJEXT)
src_tpm2_nvread_OBJECTS = $(am_src_tpm2_nvread_OBJECTS)
src_tpm2_nvread_LDADD = $(LDADD)
src_tpm2_nvread_DEPENDENCIES = src/libcommon.a
am_src_tpm2_nvreadlock_OBJECTS = src/tpm2_nvreadlock.$(OBJEXT)
src_tpm2_nvreadlock_OBJECTS = $(am_src_tpm2_nvreadlock_OBJECTS)
src_tpm2_nvreadlock_LDADD = $(LDADD)
src_tpm2_nvreadlock_DEPENDENCIES = src/libcommon.a
am_src_tpm2_nvrelease_OBJECTS = src/tpm2_nvrelease.$(OBJEXT)
src_tpm2_nvrelease_OBJECTS = $(am_src_tpm2_nvrelease_OBJECTS)
src_tpm2_nvrelease_LDADD = $(LDADD)
src_tpm2_nvrelease_DEPENDENCIES = src/libcommon.a
am_src_tpm2_nvwrite_OBJECTS = src/tpm2_nvwrite.$(OBJEXT)
src_tpm2_nvwrite_OBJECTS = $(am_src_tpm2_nvwrite_OBJECTS)
src_tpm2_nvwrite_LDADD = $(LDADD)
src_tpm2_nvwrite_DEPENDENCIES = src/libcommon.a
am_src_tpm2_quote_OBJECTS = src/tpm2_quote.$(OBJEXT)
src_tpm2_quote_OBJECTS = $(am_src_tpm2_quote_OBJECTS)
src_tpm2_quote_LDADD = $(LDADD)
src_tpm2_quote_DEPENDENCIES = src/libcommon.a
am_src_tpm2_readpublic_OBJECTS = src/tpm2_readpublic.$(OBJEXT)
src_tpm2_readpublic_OBJECTS = $(am_src_tpm2_readpublic_OBJECTS)
src_tpm2_readpublic_LDADD = $(LDADD)
src_tpm2_readpublic_DEPENDENCIES = src/libcommon.a
am_src_tpm2_rsadecrypt_OBJECTS = src/tpm2_rsadecrypt.$(OBJEXT)
src_tpm2_rsadecrypt_OBJECTS = $(am_src_tpm2_rsadecrypt_OBJECTS)
src_tpm2_rsadecrypt_LDADD = $(LDADD)
src_tpm2_rsadecrypt_DEPENDENCIES = src/libcommon.a
am_src_tpm2_rsaencrypt_OBJECTS = src/tpm2_rsaencrypt.$(OBJEXT)
src_tpm2_rsaencrypt_OBJECTS = $(am_src_tpm2_rsaencrypt_OBJECTS)
src_tpm2_rsaencrypt_LDADD = $(LDADD)
src_tpm2_rsaencrypt_DEPENDENCIES = src/libcommon.a
am_src_tpm2_sign_OBJECTS = src/tpm2_sign.$(OBJEXT)
src_tpm2_sign_OBJECTS = $(am_src_tpm2_sign_OBJECTS)
src_tpm2_sign_LDADD = $(LDADD)
src_tpm2_sign_DEPENDENCIES = src/libcommon.a
am_src_tpm2_takeownership_OBJECTS = src/tpm2_takeownership.$(OBJEXT)
src_tpm2_takeownership_OBJECTS = $(am_src_tpm2_takeownership_OBJECTS)
src_tpm2_takeownership_LDADD = $(LDADD)
src_tpm2_takeownership_DEPENDENCIES = src/libcommon.a
am_src_tpm2_unseal_OBJECTS = src/tpm2_unseal.$(OBJEXT)
src_tpm2_unseal_OBJECTS = $(am_src_tpm2_unseal_OBJECTS)
src_tpm2_unseal_LDADD = $(LDADD)
src_tpm2_unseal_DEPENDENCIES = src/libcommon.a
am_src_tpm2_verifysignature_OBJECTS =  \
	src/tpm2_verifysignature.$(OBJEXT)
src_tpm2_verifysignature_OBJECTS =  \
	$(am_src_tpm2_verifysignature_OBJECTS)
src_tpm2_verifysignature_LDADD = $(LDADD)
src_tpm2_verifysignature_DEPENDENCIES = src/libcommon.a
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(src_libcommon_a_SOURCES) \
	$(src_tpm2_activatecredential_SOURCES) \
	$(src_tpm2_akparse_SOURCES) $(src_tpm2_certify_SOURCES) \
	$(src_tpm2_create_SOURCES) $(src_tpm2_createprimary_SOURCES) \
	$(src_tpm2_encryptdecrypt_SOURCES) \
	$(src_tpm2_evictcontrol_SOURCES) \
	$(src_tpm2_getmanufec_SOURCES) $(src_tpm2_getpubak_SOURCES) \
	$(src_tpm2_getpubek_SOURCES) $(src_tpm2_getrandom_SOURCES) \
	$(src_tpm2_hash_SOURCES) $(src_tpm2_hmac_SOURCES) \
	$(src_tpm2_listpcrs_SOURCES) $(src_tpm2_load_SOURCES) \
	$(src_tpm2_loadexternal_SOURCES) \
	$(src_tpm2_makecredential_SOURCES) \
	$(src_tpm2_nvdefine_SOURCES) $(src_tpm2_nvlist_SOURCES) \
	$(src_tpm2_nvread_SOURCES) $(src_tpm2_nvrelease_SOURCES) \
	$(src_tpm2_nvreadlock_SOURCES) \
	$(src_tpm2_nvwrite_SOURCES) $(src_tpm2_quote_SOURCES) \
	$(src_tpm2_readpublic_SOURCES) $(src_tpm2_rsadecrypt_SOURCES) \
	$(src_tpm2_rsaencrypt_SOURCES) $(src_tpm2_sign_SOURCES) \
	$(src_tpm2_takeownership_SOURCES) $(src_tpm2_unseal_SOURCES) \
	$(src_tpm2_verifysignature_SOURCES)
DIST_SOURCES = $(src_libcommon_a_SOURCES) \
	$(src_tpm2_activatecredential_SOURCES) \
	$(src_tpm2_akparse_SOURCES) $(src_tpm2_certify_SOURCES) \
	$(src_tpm2_create_SOURCES) $(src_tpm2_createprimary_SOURCES) \
	$(src_tpm2_encryptdecrypt_SOURCES) \
	$(src_tpm2_evictcontrol_SOURCES) \
	$(src_tpm2_getmanufec_SOURCES) $(src_tpm2_getpubak_SOURCES) \
	$(src_tpm2_getpubek_SOURCES) $(src_tpm2_getrandom_SOURCES) \
	$(src_tpm2_hash_SOURCES) $(src_tpm2_hmac_SOURCES) \
	$(src_tpm2_listpcrs_SOURCES) $(src_tpm2_load_SOURCES) \
	$(src_tpm2_loadexternal_SOURCES) \
	$(src_tpm2_makecredential_SOURCES) \
	$(src_tpm2_nvdefine_SOURCES) $(src_tpm2_nvlist_SOURCES) \
	$(src_tpm2_nvread_SOURCES) $(src_tpm2_nvrelease_SOURCES) \
	$(src_tpm2_nvreadlock_SOURCES) \
	$(src_tpm2_nvwrite_SOURCES) $(src_tpm2_quote_SOURCES) \
	$(src_tpm2_readpublic_SOURCES) $(src_tpm2_rsadecrypt_SOURCES) \
	$(src_tpm2_rsaencrypt_SOURCES) $(src_tpm2_sign_SOURCES) \
	$(src_tpm2_takeownership_SOURCES) $(src_tpm2_unseal_SOURCES) \
	$(src_tpm2_verifysignature_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = aclocal-1.14
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = autoconf
AUTOHEADER = autoheader
AUTOMAKE = automake-1.14
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"tpm2.0-tools\" -DPACKAGE_TARNAME=\"tpm2-0-tools\" -DPACKAGE_VERSION=\"1.0.0\" -DPACKAGE_STRING=\"tpm2.0-tools\ 1.0.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"tpm2-0-tools\" -DVERSION=\"1.0.0\" -DHAVE_TPM20_H=1 -DHAVE_TCTI_SOCKET_H=1 -DHAVE_OPENSSL_H=1 -DHAVE_CURL_H=1 -DHAVE_LIBTSS2=1 -DHAVE_LIBCRYPTO=1 -DHAVE_LIBCURL=1
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = -lcurl -lcrypto -ltss2 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = tpm2-0-tools
PACKAGE_BUGREPORT = 
PACKAGE_NAME = tpm2.0-tools
PACKAGE_STRING = tpm2.0-tools 1.0.0
PACKAGE_TARNAME = tpm2-0-tools
PACKAGE_URL = 
PACKAGE_VERSION = 1.0.0
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 1.0.0
abs_builddir = /usr/src/tpm2.0-tools
abs_srcdir = /usr/src/tpm2.0-tools
abs_top_builddir = /usr/src/tpm2.0-tools
abs_top_srcdir = /usr/src/tpm2.0-tools
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /root/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
INCLUDE_DIRS = -I$(srcdir)
AM_CFLAGS = -DSAPI_CLIENT $(INCLUDE_DIRS)
AM_CXXFLAGS = -DSAPI_CLIENT $(INCLUDE_DIRS)
LDADD = src/libcommon.a -ltctisocket
noinst_LIBRARIES = src/libcommon.a
COMMON_SRC = \
    src/common.c \
    src/debug.c \
    src/syscontext.c \
    src/CatSizedByteBuffer.c \
    src/CopySizedBuffer.c \
    src/DecryptEncrypt.c \
    src/Entity.c \
    src/kdfa.c \
    src/LoadExternalHMACKey.c \
    src/SessionHmac.c \
    src/StartAuthSession.c \
    src/TpmCalcPHash.c \
    src/TpmHandleToName.c \
    src/TpmHash.c \
    src/TpmHmac.c

src_libcommon_a_SOURCES = $(COMMON_SRC)
src_tpm2_listpcrs_SOURCES = src/tpm2_listpcrs.cpp
src_tpm2_quote_SOURCES = src/tpm2_quote.cpp
src_tpm2_takeownership_SOURCES = src/tpm2_takeownership.cpp
src_tpm2_getpubek_SOURCES = src/tpm2_getpubek.cpp
src_tpm2_getpubak_SOURCES = src/tpm2_getpubak.cpp
src_tpm2_getmanufec_SOURCES = src/tpm2_getmanufec.cpp
src_tpm2_akparse_SOURCES = src/tpm2_akparse.cpp
src_tpm2_makecredential_SOURCES = src/tpm2_makecredential.cpp
src_tpm2_activatecredential_SOURCES = src/tpm2_activatecredential.cpp
src_tpm2_hash_SOURCES = src/tpm2_hash.cpp
src_tpm2_nvlist_SOURCES = src/tpm2_nvlist.cpp
src_tpm2_nvread_SOURCES = src/tpm2_nvread.cpp
src_tpm2_nvreadlock_SOURCES = src/tpm2_nvreadlock.cpp
src_tpm2_nvwrite_SOURCES = src/tpm2_nvwrite.cpp
src_tpm2_nvdefine_SOURCES = src/tpm2_nvdefine.cpp
src_tpm2_nvrelease_SOURCES = src/tpm2_nvrelease.cpp
src_tpm2_createprimary_SOURCES = src/tpm2_createprimary.cpp
src_tpm2_create_SOURCES = src/tpm2_create.cpp
src_tpm2_hmac_SOURCES = src/tpm2_hmac.cpp
src_tpm2_certify_SOURCES = src/tpm2_certify.cpp
src_tpm2_readpublic_SOURCES = src/tpm2_readpublic.cpp
src_tpm2_getrandom_SOURCES = src/tpm2_getrandom.cpp
src_tpm2_encryptdecrypt_SOURCES = src/tpm2_encryptdecrypt.cpp
src_tpm2_evictcontrol_SOURCES = src/tpm2_evictcontrol.cpp
src_tpm2_load_SOURCES = src/tpm2_load.cpp
src_tpm2_loadexternal_SOURCES = src/tpm2_loadexternal.cpp
src_tpm2_rsadecrypt_SOURCES = src/tpm2_rsadecrypt.cpp
src_tpm2_rsaencrypt_SOURCES = src/tpm2_rsaencrypt.cpp
src_tpm2_sign_SOURCES = src/tpm2_sign.cpp
src_tpm2_unseal_SOURCES = src/tpm2_unseal.cpp
src_tpm2_verifysignature_SOURCES = src/tpm2_verifysignature.cpp
all: all-am

.SUFFIXES:
.SUFFIXES: .c .cpp .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/common.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/debug.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/syscontext.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/CatSizedByteBuffer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/CopySizedBuffer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/DecryptEncrypt.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/Entity.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/kdfa.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/LoadExternalHMACKey.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/SessionHmac.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/StartAuthSession.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/TpmCalcPHash.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/TpmHandleToName.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/TpmHash.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/TpmHmac.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/libcommon.a: $(src_libcommon_a_OBJECTS) $(src_libcommon_a_DEPENDENCIES) $(EXTRA_src_libcommon_a_DEPENDENCIES) src/$(am__dirstamp)
	$(AM_V_at)-rm -f src/libcommon.a
	$(AM_V_AR)$(src_libcommon_a_AR) src/libcommon.a $(src_libcommon_a_OBJECTS) $(src_libcommon_a_LIBADD)
	$(AM_V_at)$(RANLIB) src/libcommon.a
install-sbinPROGRAMS: $(sbin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(sbin_PROGRAMS)'; test -n "$(sbindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(sbindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(sbindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(sbindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(sbindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-sbinPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(sbin_PROGRAMS)'; test -n "$(sbindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(sbindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(sbindir)" && rm -f $$files

clean-sbinPROGRAMS:
	@list='$(sbin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
src/tpm2_activatecredential.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_activatecredential$(EXEEXT): $(src_tpm2_activatecredential_OBJECTS) $(src_tpm2_activatecredential_DEPENDENCIES) $(EXTRA_src_tpm2_activatecredential_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_activatecredential$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_activatecredential_OBJECTS) $(src_tpm2_activatecredential_LDADD) $(LIBS)
src/tpm2_akparse.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_akparse$(EXEEXT): $(src_tpm2_akparse_OBJECTS) $(src_tpm2_akparse_DEPENDENCIES) $(EXTRA_src_tpm2_akparse_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_akparse$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_akparse_OBJECTS) $(src_tpm2_akparse_LDADD) $(LIBS)
src/tpm2_certify.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_certify$(EXEEXT): $(src_tpm2_certify_OBJECTS) $(src_tpm2_certify_DEPENDENCIES) $(EXTRA_src_tpm2_certify_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_certify$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_certify_OBJECTS) $(src_tpm2_certify_LDADD) $(LIBS)
src/tpm2_create.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_create$(EXEEXT): $(src_tpm2_create_OBJECTS) $(src_tpm2_create_DEPENDENCIES) $(EXTRA_src_tpm2_create_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_create$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_create_OBJECTS) $(src_tpm2_create_LDADD) $(LIBS)
src/tpm2_createprimary.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_createprimary$(EXEEXT): $(src_tpm2_createprimary_OBJECTS) $(src_tpm2_createprimary_DEPENDENCIES) $(EXTRA_src_tpm2_createprimary_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_createprimary$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_createprimary_OBJECTS) $(src_tpm2_createprimary_LDADD) $(LIBS)
src/tpm2_encryptdecrypt.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_encryptdecrypt$(EXEEXT): $(src_tpm2_encryptdecrypt_OBJECTS) $(src_tpm2_encryptdecrypt_DEPENDENCIES) $(EXTRA_src_tpm2_encryptdecrypt_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_encryptdecrypt$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_encryptdecrypt_OBJECTS) $(src_tpm2_encryptdecrypt_LDADD) $(LIBS)
src/tpm2_evictcontrol.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_evictcontrol$(EXEEXT): $(src_tpm2_evictcontrol_OBJECTS) $(src_tpm2_evictcontrol_DEPENDENCIES) $(EXTRA_src_tpm2_evictcontrol_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_evictcontrol$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_evictcontrol_OBJECTS) $(src_tpm2_evictcontrol_LDADD) $(LIBS)
src/tpm2_getmanufec.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_getmanufec$(EXEEXT): $(src_tpm2_getmanufec_OBJECTS) $(src_tpm2_getmanufec_DEPENDENCIES) $(EXTRA_src_tpm2_getmanufec_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_getmanufec$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_getmanufec_OBJECTS) $(src_tpm2_getmanufec_LDADD) $(LIBS)
src/tpm2_getpubak.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_getpubak$(EXEEXT): $(src_tpm2_getpubak_OBJECTS) $(src_tpm2_getpubak_DEPENDENCIES) $(EXTRA_src_tpm2_getpubak_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_getpubak$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_getpubak_OBJECTS) $(src_tpm2_getpubak_LDADD) $(LIBS)
src/tpm2_getpubek.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_getpubek$(EXEEXT): $(src_tpm2_getpubek_OBJECTS) $(src_tpm2_getpubek_DEPENDENCIES) $(EXTRA_src_tpm2_getpubek_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_getpubek$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_getpubek_OBJECTS) $(src_tpm2_getpubek_LDADD) $(LIBS)
src/tpm2_getrandom.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_getrandom$(EXEEXT): $(src_tpm2_getrandom_OBJECTS) $(src_tpm2_getrandom_DEPENDENCIES) $(EXTRA_src_tpm2_getrandom_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_getrandom$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_getrandom_OBJECTS) $(src_tpm2_getrandom_LDADD) $(LIBS)
src/tpm2_hash.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_hash$(EXEEXT): $(src_tpm2_hash_OBJECTS) $(src_tpm2_hash_DEPENDENCIES) $(EXTRA_src_tpm2_hash_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_hash$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_hash_OBJECTS) $(src_tpm2_hash_LDADD) $(LIBS)
src/tpm2_hmac.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_hmac$(EXEEXT): $(src_tpm2_hmac_OBJECTS) $(src_tpm2_hmac_DEPENDENCIES) $(EXTRA_src_tpm2_hmac_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_hmac$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_hmac_OBJECTS) $(src_tpm2_hmac_LDADD) $(LIBS)
src/tpm2_listpcrs.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_listpcrs$(EXEEXT): $(src_tpm2_listpcrs_OBJECTS) $(src_tpm2_listpcrs_DEPENDENCIES) $(EXTRA_src_tpm2_listpcrs_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_listpcrs$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_listpcrs_OBJECTS) $(src_tpm2_listpcrs_LDADD) $(LIBS)
src/tpm2_load.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_load$(EXEEXT): $(src_tpm2_load_OBJECTS) $(src_tpm2_load_DEPENDENCIES) $(EXTRA_src_tpm2_load_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_load$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_load_OBJECTS) $(src_tpm2_load_LDADD) $(LIBS)
src/tpm2_loadexternal.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_loadexternal$(EXEEXT): $(src_tpm2_loadexternal_OBJECTS) $(src_tpm2_loadexternal_DEPENDENCIES) $(EXTRA_src_tpm2_loadexternal_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_loadexternal$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_loadexternal_OBJECTS) $(src_tpm2_loadexternal_LDADD) $(LIBS)
src/tpm2_makecredential.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_makecredential$(EXEEXT): $(src_tpm2_makecredential_OBJECTS) $(src_tpm2_makecredential_DEPENDENCIES) $(EXTRA_src_tpm2_makecredential_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_makecredential$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_makecredential_OBJECTS) $(src_tpm2_makecredential_LDADD) $(LIBS)
src/tpm2_nvdefine.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_nvdefine$(EXEEXT): $(src_tpm2_nvdefine_OBJECTS) $(src_tpm2_nvdefine_DEPENDENCIES) $(EXTRA_src_tpm2_nvdefine_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_nvdefine$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_nvdefine_OBJECTS) $(src_tpm2_nvdefine_LDADD) $(LIBS)
src/tpm2_nvlist.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_nvlist$(EXEEXT): $(src_tpm2_nvlist_OBJECTS) $(src_tpm2_nvlist_DEPENDENCIES) $(EXTRA_src_tpm2_nvlist_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_nvlist$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_nvlist_OBJECTS) $(src_tpm2_nvlist_LDADD) $(LIBS)
src/tpm2_nvread.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_nvread$(EXEEXT): $(src_tpm2_nvread_OBJECTS) $(src_tpm2_nvread_DEPENDENCIES) $(EXTRA_src_tpm2_nvread_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_nvread$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_nvread_OBJECTS) $(src_tpm2_nvread_LDADD) $(LIBS)
src/tpm2_nvreadlock.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_nvreadlock$(EXEEXT): $(src_tpm2_nvreadlock_OBJECTS) $(src_tpm2_nvreadlock_DEPENDENCIES) $(EXTRA_src_tpm2_nvreadlock_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_nvreadlock$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_nvreadlock_OBJECTS) $(src_tpm2_nvreadlock_LDADD) $(LIBS)
src/tpm2_nvrelease.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_nvrelease$(EXEEXT): $(src_tpm2_nvrelease_OBJECTS) $(src_tpm2_nvrelease_DEPENDENCIES) $(EXTRA_src_tpm2_nvrelease_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_nvrelease$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_nvrelease_OBJECTS) $(src_tpm2_nvrelease_LDADD) $(LIBS)
src/tpm2_nvwrite.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_nvwrite$(EXEEXT): $(src_tpm2_nvwrite_OBJECTS) $(src_tpm2_nvwrite_DEPENDENCIES) $(EXTRA_src_tpm2_nvwrite_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_nvwrite$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_nvwrite_OBJECTS) $(src_tpm2_nvwrite_LDADD) $(LIBS)
src/tpm2_quote.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_quote$(EXEEXT): $(src_tpm2_quote_OBJECTS) $(src_tpm2_quote_DEPENDENCIES) $(EXTRA_src_tpm2_quote_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_quote$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_quote_OBJECTS) $(src_tpm2_quote_LDADD) $(LIBS)
src/tpm2_readpublic.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_readpublic$(EXEEXT): $(src_tpm2_readpublic_OBJECTS) $(src_tpm2_readpublic_DEPENDENCIES) $(EXTRA_src_tpm2_readpublic_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_readpublic$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_readpublic_OBJECTS) $(src_tpm2_readpublic_LDADD) $(LIBS)
src/tpm2_rsadecrypt.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_rsadecrypt$(EXEEXT): $(src_tpm2_rsadecrypt_OBJECTS) $(src_tpm2_rsadecrypt_DEPENDENCIES) $(EXTRA_src_tpm2_rsadecrypt_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_rsadecrypt$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_rsadecrypt_OBJECTS) $(src_tpm2_rsadecrypt_LDADD) $(LIBS)
src/tpm2_rsaencrypt.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_rsaencrypt$(EXEEXT): $(src_tpm2_rsaencrypt_OBJECTS) $(src_tpm2_rsaencrypt_DEPENDENCIES) $(EXTRA_src_tpm2_rsaencrypt_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_rsaencrypt$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_rsaencrypt_OBJECTS) $(src_tpm2_rsaencrypt_LDADD) $(LIBS)
src/tpm2_sign.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_sign$(EXEEXT): $(src_tpm2_sign_OBJECTS) $(src_tpm2_sign_DEPENDENCIES) $(EXTRA_src_tpm2_sign_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_sign$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_sign_OBJECTS) $(src_tpm2_sign_LDADD) $(LIBS)
src/tpm2_takeownership.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_takeownership$(EXEEXT): $(src_tpm2_takeownership_OBJECTS) $(src_tpm2_takeownership_DEPENDENCIES) $(EXTRA_src_tpm2_takeownership_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_takeownership$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_takeownership_OBJECTS) $(src_tpm2_takeownership_LDADD) $(LIBS)
src/tpm2_unseal.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_unseal$(EXEEXT): $(src_tpm2_unseal_OBJECTS) $(src_tpm2_unseal_DEPENDENCIES) $(EXTRA_src_tpm2_unseal_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_unseal$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_unseal_OBJECTS) $(src_tpm2_unseal_LDADD) $(LIBS)
src/tpm2_verifysignature.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

src/tpm2_verifysignature$(EXEEXT): $(src_tpm2_verifysignature_OBJECTS) $(src_tpm2_verifysignature_DEPENDENCIES) $(EXTRA_src_tpm2_verifysignature_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/tpm2_verifysignature$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(src_tpm2_verifysignature_OBJECTS) $(src_tpm2_verifysignature_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/CatSizedByteBuffer.Po
include src/$(DEPDIR)/CopySizedBuffer.Po
include src/$(DEPDIR)/DecryptEncrypt.Po
include src/$(DEPDIR)/Entity.Po
include src/$(DEPDIR)/LoadExternalHMACKey.Po
include src/$(DEPDIR)/SessionHmac.Po
include src/$(DEPDIR)/StartAuthSession.Po
include src/$(DEPDIR)/TpmCalcPHash.Po
include src/$(DEPDIR)/TpmHandleToName.Po
include src/$(DEPDIR)/TpmHash.Po
include src/$(DEPDIR)/TpmHmac.Po
include src/$(DEPDIR)/common.Po
include src/$(DEPDIR)/debug.Po
include src/$(DEPDIR)/kdfa.Po
include src/$(DEPDIR)/syscontext.Po
include src/$(DEPDIR)/tpm2_activatecredential.Po
include src/$(DEPDIR)/tpm2_akparse.Po
include src/$(DEPDIR)/tpm2_certify.Po
include src/$(DEPDIR)/tpm2_create.Po
include src/$(DEPDIR)/tpm2_createprimary.Po
include src/$(DEPDIR)/tpm2_encryptdecrypt.Po
include src/$(DEPDIR)/tpm2_evictcontrol.Po
include src/$(DEPDIR)/tpm2_getmanufec.Po
include src/$(DEPDIR)/tpm2_getpubak.Po
include src/$(DEPDIR)/tpm2_getpubek.Po
include src/$(DEPDIR)/tpm2_getrandom.Po
include src/$(DEPDIR)/tpm2_hash.Po
include src/$(DEPDIR)/tpm2_hmac.Po
include src/$(DEPDIR)/tpm2_listpcrs.Po
include src/$(DEPDIR)/tpm2_load.Po
include src/$(DEPDIR)/tpm2_loadexternal.Po
include src/$(DEPDIR)/tpm2_makecredential.Po
include src/$(DEPDIR)/tpm2_nvdefine.Po
include src/$(DEPDIR)/tpm2_nvlist.Po
include src/$(DEPDIR)/tpm2_nvread.Po
include src/$(DEPDIR)/tpm2_nvreadlock.Po
include src/$(DEPDIR)/tpm2_nvrelease.Po
include src/$(DEPDIR)/tpm2_nvwrite.Po
include src/$(DEPDIR)/tpm2_quote.Po
include src/$(DEPDIR)/tpm2_readpublic.Po
include src/$(DEPDIR)/tpm2_rsadecrypt.Po
include src/$(DEPDIR)/tpm2_rsaencrypt.Po
include src/$(DEPDIR)/tpm2_sign.Po
include src/$(DEPDIR)/tpm2_takeownership.Po
include src/$(DEPDIR)/tpm2_unseal.Po
include src/$(DEPDIR)/tpm2_verifysignature.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf src/.libs src/_libs

distclean-libtool:
	-rm -f libtool config.lt

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES) $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(sbindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-noinstLIBRARIES \
	clean-sbinPROGRAMS mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-sbinPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-sbinPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-cscope clean-generic clean-libtool clean-noinstLIBRARIES \
	clean-sbinPROGRAMS cscope cscopelist-am ctags ctags-am dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-sbinPROGRAMS install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-sbinPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
