site_name: tpm2-tools

docs_dir: docs

theme: readthedocs

nav:
    - Home: README.md
    - INSTALL: INSTALL.md
    - tpm2: man/tpm2.1.md
    - tpm2_activatecredential: man/tpm2_activatecredential.1.md
    - tpm2_certify: man/tpm2_certify.1.md
    - tpm2_certifycreation: man/tpm2_certifycreation.1.md
    - tpm2_certifyX509certutil: man/tpm2_certifyX509certutil.1.md
    - tpm2_changeauth: man/tpm2_changeauth.1.md
    - tpm2_changeeps: man/tpm2_changeeps.1.md
    - tpm2_changepps: man/tpm2_changepps.1.md
    - tpm2_checkquote: man/tpm2_checkquote.1.md
    - tpm2_clear: man/tpm2_clear.1.md
    - tpm2_clearcontrol: man/tpm2_clearcontrol.1.md
    - tpm2_clockrateadjust: man/tpm2_clockrateadjust.1.md
    - tpm2_commit: man/tpm2_commit.1.md
    - tpm2_create: man/tpm2_create.1.md
    - tpm2_createak: man/tpm2_createak.1.md
    - tpm2_createek: man/tpm2_createek.1.md
    - tpm2_createpolicy: man/tpm2_createpolicy.1.md
    - tpm2_createprimary: man/tpm2_createprimary.1.md
    - tpm2_dictionarylockout: man/tpm2_dictionarylockout.1.md
    - tpm2_duplicate: man/tpm2_duplicate.1.md
    - tpm2_ecdhkeygen: man/tpm2_ecdhkeygen.1.md
    - tpm2_ecdhzgen: man/tpm2_ecdhzgen.1.md
    - tpm2_ecephemeral: man/tpm2_ecephemeral.1.md
    - tpm2_encryptdecrypt: man/tpm2_encryptdecrypt.1.md
    - tpm2_eventlog: man/tpm2_eventlog.1.md
    - tpm2_evictcontrol: man/tpm2_evictcontrol.1.md
    - tpm2_flushcontext: man/tpm2_flushcontext.1.md
    - tpm2_getcap: man/tpm2_getcap.1.md
    - tpm2_getcommandauditdigest: man/tpm2_getcommandauditdigest.1.md
    - tpm2_geteccparameters: man/tpm2_geteccparameters.1.md
    - tpm2_getekcertificate: man/tpm2_getekcertificate.1.md
    - tpm2_getrandom: man/tpm2_getrandom.1.md
    - tpm2_getsessionauditdigest: man/tpm2_getsessionauditdigest.1.md
    - tpm2_gettestresult: man/tpm2_gettestresult.1.md
    - tpm2_gettime: man/tpm2_gettime.1.md
    - tpm2_hash: man/tpm2_hash.1.md
    - tpm2_hierarchycontrol: man/tpm2_hierarchycontrol.1.md
    - tpm2_hmac: man/tpm2_hmac.1.md
    - tpm2_import: man/tpm2_import.1.md
    - tpm2_incrementalselftest: man/tpm2_incrementalselftest.1.md
    - tpm2_load: man/tpm2_load.1.md
    - tpm2_loadexternal: man/tpm2_loadexternal.1.md
    - tpm2_makecredential: man/tpm2_makecredential.1.md
    - tpm2_nvcertify: man/tpm2_nvcertify.1.md
    - tpm2_nvdefine: man/tpm2_nvdefine.1.md
    - tpm2_nvextend: man/tpm2_nvextend.1.md
    - tpm2_nvincrement: man/tpm2_nvincrement.1.md
    - tpm2_nvread: man/tpm2_nvread.1.md
    - tpm2_nvreadlock: man/tpm2_nvreadlock.1.md
    - tpm2_nvreadpublic: man/tpm2_nvreadpublic.1.md
    - tpm2_nvsetbits: man/tpm2_nvsetbits.1.md
    - tpm2_nvundefine: man/tpm2_nvundefine.1.md
    - tpm2_nvwrite: man/tpm2_nvwrite.1.md
    - tpm2_nvwritelock: man/tpm2_nvwritelock.1.md
    - tpm2_pcrallocate: man/tpm2_pcrallocate.1.md
    - tpm2_pcrevent: man/tpm2_pcrevent.1.md
    - tpm2_pcrextend: man/tpm2_pcrextend.1.md
    - tpm2_pcrread: man/tpm2_pcrread.1.md
    - tpm2_pcrreset: man/tpm2_pcrreset.1.md
    - tpm2_policyauthorize: man/tpm2_policyauthorize.1.md
    - tpm2_policyauthorizenv: man/tpm2_policyauthorizenv.1.md
    - tpm2_policyauthvalue: man/tpm2_policyauthvalue.1.md
    - tpm2_policycommandcode: man/tpm2_policycommandcode.1.md
    - tpm2_policycountertimer: man/tpm2_policycountertimer.1.md
    - tpm2_policycphash: man/tpm2_policycphash.1.md
    - tpm2_policyduplicationselect: man/tpm2_policyduplicationselect.1.md
    - tpm2_policylocality: man/tpm2_policylocality.1.md
    - tpm2_policynamehash: man/tpm2_policynamehash.1.md
    - tpm2_policynv: man/tpm2_policynv.1.md
    - tpm2_policynvwritten: man/tpm2_policynvwritten.1.md
    - tpm2_policyor: man/tpm2_policyor.1.md
    - tpm2_policypassword: man/tpm2_policypassword.1.md
    - tpm2_policypcr: man/tpm2_policypcr.1.md
    - tpm2_policyrestart: man/tpm2_policyrestart.1.md
    - tpm2_policysecret: man/tpm2_policysecret.1.md
    - tpm2_policysigned: man/tpm2_policysigned.1.md
    - tpm2_policytemplate: man/tpm2_policytemplate.1.md
    - tpm2_policyticket: man/tpm2_policyticket.1.md
    - tpm2_print: man/tpm2_print.1.md
    - tpm2_quote: man/tpm2_quote.1.md
    - tpm2_rc_decode: man/tpm2_rc_decode.1.md
    - tpm2_readclock: man/tpm2_readclock.1.md
    - tpm2_readpublic: man/tpm2_readpublic.1.md
    - tpm2_rsadecrypt: man/tpm2_rsadecrypt.1.md
    - tpm2_rsaencrypt: man/tpm2_rsaencrypt.1.md
    - tpm2_selftest: man/tpm2_selftest.1.md
    - tpm2_send: man/tpm2_send.1.md
    - tpm2_sessionconfig: man/tpm2_sessionconfig.1.md
    - tpm2_setclock: man/tpm2_setclock.1.md
    - tpm2_setcommandauditstatus: man/tpm2_setcommandauditstatus.1.md
    - tpm2_setprimarypolicy: man/tpm2_setprimarypolicy.1.md
    - tpm2_shutdown: man/tpm2_shutdown.1.md
    - tpm2_sign: man/tpm2_sign.1.md
    - tpm2_startauthsession: man/tpm2_startauthsession.1.md
    - tpm2_startup: man/tpm2_startup.1.md
    - tpm2_stirrandom: man/tpm2_stirrandom.1.md
    - tpm2_testparms: man/tpm2_testparms.1.md
    - tpm2_unseal: man/tpm2_unseal.1.md
    - tpm2_verifysignature: man/tpm2_verifysignature.1.md
    - tpm2_zgen2phase: man/tpm2_zgen2phase.1.md
    - tss2_authorizepolicy: man/tss2_authorizepolicy.1.md
    - tss2_changeauth: man/tss2_changeauth.1.md
    - tss2_createkey: man/tss2_createkey.1.md
    - tss2_createnv: man/tss2_createnv.1.md
    - tss2_createseal: man/tss2_createseal.1.md
    - tss2_decrypt: man/tss2_decrypt.1.md
    - tss2_delete: man/tss2_delete.1.md
    - tss2_encrypt: man/tss2_encrypt.1.md
    - tss2_exportkey: man/tss2_exportkey.1.md
    - tss2_exportpolicy: man/tss2_exportpolicy.1.md
    - tss2_getappdata: man/tss2_getappdata.1.md
    - tss2_getcertificate: man/tss2_getcertificate.1.md
    - tss2_getdescription: man/tss2_getdescription.1.md
    - tss2_getinfo: man/tss2_getinfo.1.md
    - tss2_getplatformcertificates: man/tss2_getplatformcertificates.1.md
    - tss2_getrandom: man/tss2_getrandom.1.md
    - tss2_gettpmblobs: man/tss2_gettpmblobs.1.md
    - tss2_import: man/tss2_import.1.md
    - tss2_list: man/tss2_list.1.md
    - tss2_nvextend: man/tss2_nvextend.1.md
    - tss2_nvincrement: man/tss2_nvincrement.1.md
    - tss2_nvread: man/tss2_nvread.1.md
    - tss2_nvsetbits: man/tss2_nvsetbits.1.md
    - tss2_nvwrite: man/tss2_nvwrite.1.md
    - tss2_pcrextend: man/tss2_pcrextend.1.md
    - tss2_pcrread: man/tss2_pcrread.1.md
    - tss2_provision: man/tss2_provision.1.md
    - tss2_quote: man/tss2_quote.1.md
    - tss2_setappdata: man/tss2_setappdata.1.md
    - tss2_setcertificate: man/tss2_setcertificate.1.md
    - tss2_setdescription: man/tss2_setdescription.1.md
    - tss2_sign: man/tss2_sign.1.md
    - tss2_unseal: man/tss2_unseal.1.md
    - tss2_verifyquote: man/tss2_verifyquote.1.md
    - tss2_verifysignature: man/tss2_verifysignature.1.md
    - tss2_writeauthorizenv: man/tss2_writeauthorizenv.1.md
